---
- name: Update and run Ukuvota 
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Update the repository
      git:
        repo: https://github.com/waotzi/ukuvota.git
        dest: /var/www/ukuvota.world
        update: yes
      register: git_pull

    - name: Install packages
      npm:
        path: /var/www/ukuvota.world
        state: present
        global: no
      when: git_pull.changed

    - name: Build the application
      command: npm run build
      args:
        chdir: /var/www/ukuvota.world
      when: git_pull.changed

    - name: Sync dist directory with build directory
      synchronize:
        src: /var/www/ukuvota.world/dist/
        dest: /var/www/ukuvota.world/build/
        delete: true
      when: git_pull.changed 

    - name: Restart the application
      command: pm2 restart 0
      when: git_pull.changed
