---
- name: Update and run Ukuvota
  hosts: localhost
  gather_facts: false

  vars:
    artifact_url: "{{ extra_vars.artifact_url }}"
    backup_dir: "/root/backups/ukuvota"
    current_datetime: "{{ ansible_date_time.iso8601_basic }}"
    backup_filename: "db_backup_{{ current_datetime }}.zip"

  tasks:
    - name: Download artifact from Github
      get_url:
        url: "{{ artifact_url }}"
        dest: /tmp/ukuvota.zip

    - name: Backup database
      shell: "cd /var/www/ukuvota.world && zip -r {{ backup_dir }}/{{ backup_filename }} db"
      register: db_backup

    - name: Unzip artifact to /var/www/ukuvota.world
      unarchive:
        src: /tmp/ukuvota.zip
        dest: /var/www/ukuvota.world
        remote_src: yes
        extra_opts: [--overwrite]
      when: db_backup|success

    - name: Restart the application
      command: pm2 restart 0
      when: db_backup|success.changed
