---
- name: Update and run Ukuvota 
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Update the repository
      git:
        repo: https://github.com/waotzi/ukuvota.git
        dest: /var/www/ukuvota.world
        update: yes
        force: yes
      register: git_pull

    - name: Install packages
      command: npm install
      args:
        chdir: /var/www/ukuvota.world
      when: git_pull.changed
    
