---
- name: Update and run Ukuvota 
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Update the repository
      git:
        repo: https://github.com/waotzi/ukuvota.git
        dest: /var/www/ukuvota.world
        update: yes
        force: yes
      register: git_pull

    - name: Install packages and build
      npm:
        path: /var/www/ukuvota.world
        state: present
        global: no
      when: git_pull.changed

    - name: Move built files to deployment directory
      command: mv /var/www/ukuvota.world/dist /var/www/ukuvota.world/deploy
      when: git_pull.changed

    - name: Restart the application
      command: pm2 restart 0
      when: git_pull.changed
