---
- name: Update and run Ukuvota
  hosts: localhost

  vars:
    github_user: "waotzi"
    github_repo: "ukuvota"
    backup_dir: "/root/backup/ukuvota"
    backup_filename: "db_backup_{{ ansible_date_time.iso8601_basic }}.zip"

  tasks:
    - name: Get Artifact ID
      shell: "gh api -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28' /repos/{{ github_user }}/{{ github_repo }}/actions/artifacts | jq '.artifacts[0].id'"
      register: artifact_id

    - name: Get Archive Download URL
      shell: "gh api -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28' /repos/{{ github_user }}/{{ github_repo }}/actions/artifacts/{{ artifact_id.stdout }}/zip > /tmp/ukuvota.zip"

    - name: Create backup directory if not exists
      file:
        path: "{{ backup_dir }}"
        state: directory

    - name: Backup database
      shell: "cd /var/www/ukuvota.world && zip -r {{ backup_dir }}/{{ backup_filename }} db"
      register: db_backup
      when: backup_dir is defined
    
    - name: Remove dist folder if present
      file:
        path: /var/www/ukuvota.world/dist
        state: absent
      become: true
      when: db_backup.rc == 0

    - name: Create dist directory if not present
      file:
        path: /var/www/ukuvota.world/dist
        state: directory
      become: true
      when: db_backup.rc == 0

    - name: Unzip artifact to /var/www/ukuvota.world/dist
      unarchive:
        src: /tmp/ukuvota.zip
        dest: /var/www/ukuvota.world/dist
        remote_src: yes
        extra_opts: [--overwrite]
      when: db_backup.rc == 0

    - name: Restart the application
      command: pm2 restart 0
      when: db_backup.rc == 0
