---
- name: Update and run Ukuvota
  hosts: localhost
  gather_facts: false

  vars:
    backup_dir: "/root/backups/ukuvota"
    current_datetime: "{{ ansible_date_time.iso8601_basic }}"
    backup_filename: "db_backup_{{ current_datetime }}.zip"

  tasks:
    - name: Get the latest artifact from Github
      command: "gh api -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28' /repos/waotzi/ukuvota/actions/artifacts | jq '.artifacts[0].id'"
      register: artifact_id

    - name: Download artifact from Github
      command: "gh api -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28' /repos/waotzi/ukuvota/actions/artifacts/{{ artifact_id.stdout }} --jq=archive_download_url"
      register: download_url

    - name: Save the artifact to /tmp
      get_url:
        url: "{{ download_url.stdout | trim }}"
        dest: /tmp/ukuvota.zip
        
    - name: Backup database
      shell: "cd /var/www/ukuvota.world && zip -r {{ backup_dir }}/{{ backup_filename }} db"
      register: db_backup

    - name: Unzip artifact to /var/www/ukuvota.world
      unarchive:
        src: /tmp/ukuvota.zip
        dest: /var/www/ukuvota.world
        remote_src: yes
        extra_opts: [--overwrite]
      when: db_backup|success

    - name: Restart the application
      command: pm2 restart 0
      when: db_backup|success.changed
