---
- name: Update and run Ukuvota
  hosts: localhost

  vars:
    github_user: "waotzi"
    github_repo: "ukuvota"
    backup_dir: "/root/backups/ukuvota"
    backup_filename: "db_backup_{{ ansible_date_time.iso8601_basic }}.zip"

  tasks:
    - name: Get Artifact ID
      shell: "gh api -H 'Accept: application/vnd.github+json' -H 'X-GitHub-Api-Version: 2022-11-28' /repos/{{ github_user }}/{{ github_repo }}/actions/artifacts | jq '.artifacts[0].id'"
      register: artifact_id

    - name: Get Archive Download URL
      shell: curl -L "https://api.github.com/repos/{{ github_user }}/{{ github_repo }}/actions/artifacts/{{ artifact_id.stdout }}/zip" -o /tmp/ukuvota.zip
      register: archive_url

    - name: Backup database
      shell: "cd /var/www/ukuvota.world && zip -r {{ backup_dir }}/{{ backup_filename }} db"
      register: db_backup

    - name: Unzip artifact to /var/www/ukuvota.world
      unarchive:
        src: /tmp/ukuvota.zip
        dest: /var/www/ukuvota.world
        remote_src: yes
        extra_opts: [--overwrite]
      when: db_backup|success

    - name: Restart the application
      command: pm2 restart 0
      when: db_backup|success.changed
