---
- name: Update and build waotzi
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Check if the directory exists
      stat:
        path: /var/www/waotzi.org
      register: dir_check

    - name: Clone the repository if it doesn't exist
      git:
        repo: https://github.com/waotzi/website.git
        dest: /var/www/waotzi.org
        version: master
      when: not dir_check.stat.exists

    - name: Update the repository if it exists
      git:
        repo: https://github.com/waotzi/website.git
        dest: /var/www/waotzi.org
        update: yes
      register: git_pull
      when: dir_check.stat.exists

    - name: Build waotzi
      command: lua build.lua
      args:
        chdir: /var/www/waotzi.org
      when: git_pull.changed or not dir_check.stat.exists
